apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-wrapper.name" . }}-clusterrole-binding
  labels:
    {{- include "kafka-wrapper.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka-wrapper.name" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-wrapper.name" . }}-sa