apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-wrapper.name" . }}
  labels:
    {{- include "kafka-wrapper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    {{- include "kafka-wrapper.selectorLabels" . | nindent 4 }}
