{{- if index .Values "KafkaIngressWrapper" "enable" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-ingress-wrapper.name" . }}
  labels:
    {{- include "kafka-ingress-wrapper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 3000
  selector:
    {{- include "kafka-ingress-wrapper.selectorLabels" . | nindent 4 }}

{{- end }}