kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: eric-adc-k6-data-collection-controller-policy
  labels:
    app.kubernetes.io/name : eric-oss-data-collection-controller
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name : eric-oss-data-collection-controller
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name : eric-oss-adc-app-engineering