apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-fls-notifier.fullname" . }}
  labels:
    {{- include "eric-oss-fls-notifier.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eric-oss-fls-notifier.selectorLabels" . | nindent 4 }}

