{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
{{- if eq (include "eric-data-document-database-pg.isMigrationRequired" .) "true" -}}
  {{- include "eric-data-document-database-pg.networkPolicyHook" .}}
{{- end -}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}