{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- if eq (include "eric-data-document-database-pg.isMigrationRequired" .) "true" -}}
  {{- include "eric-data-document-database-pg.restorePGDataJob" .}}
{{- end -}}
{{- end }}